[package]
name = "termux-api-rs"
version = "0.0.0"
edition = "2021"

[lib]
crate_type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0.178", features = ["derive"] }
serde_json = "1.0.104"

[profile.release]
strip = true  # Automatically strip symbols from the binary.

